### ISSUE TITLE
bug:  Columns of data type `BIT` are causing JSONSchema validation issue for Targets

### ISSUE THREAD

**Issue by BuzzCutNorman** [BuzzCutNorman/tap-mssql#59]
Joshua Janicas brought to my attention in Slack an issue he had writing to `target-jsonl`.  The traceback showed the issue was with a column that has the data type `BIT`. 

```
2023-06-22T18:32:25.908428Z [info     ] Traceback (most recent call last): cmd_type=elb consumer=True name=target-jsonl  File  validators[o['stream']].validate((o['record'])) 
target-jsonl\venv\lib\site-packages\jsonschema\validators.py", line 130, in validate 
True is not of type 'string'
Failed validating 'type' in schema['properties']['IsFilterable']: {'type': ['string']} 
On instance['IsFilterable']:   True                       
```

https://meltano.slack.com/archives/C01TCRBBJD7/p1687459077893099

**Comment by BuzzCutNorman** [comment]
This is the SQL to generate a test table.
```
/*********************************
Create the simple test table
in an MSSQL database
*********************************/
DROP TABLE IF EXISTS [TestTable];
CREATE TABLE TestTable (
    Id int IDENTITY(1,1) PRIMARY KEY,
    TestColumn1 BIT NOT NULL,
    TestColumn2 BIT NOT NULL
);

/*********************************
Insert some test data into the
test table
*********************************/
INSERT INTO [testdata].[dbo].[TestTable]
           ([TestColumn1],
            [TestColumn2]
           )
     VALUES
           (0,1)
;
```

**Comment by BuzzCutNorman** [comment]
The command `meltano invoke tap-mssql` generated the following `SCHEMA` and `RECORD` messages.  The schema message has the same description for `TestColumn1` and `TestColumn2` that was present in the traceback for the column `IsFilterable`.

```
{"type": "SCHEMA", "stream": "dbo-TestTable", "schema": {"properties": {"Id": {"type": ["integer"]}, "TestColumn1": {"type": ["string"]}, "TestColumn2": {"type": ["string"]}}, "type": "object", "required": ["Id", "TestColumn1", "TestColumn2"]}, "key_properties": ["Id"]}
{"type": "RECORD", "stream": "dbo-TestTable", "record": {"Id": 1, "TestColumn1": false, "TestColumn2": true}, "time_extracted": "2023-06-22T19:44:45.198719+00:00"}
```

**Comment by BuzzCutNorman** [comment]
Running `meltano run tap-mssql target-jsonl` in the test setup lead to the same traceback posted to Slack.  

```
File "C:\development\projects\my-test-stuff\.meltano\loaders\target-jsonl\venv\lib\site-packages\target_jsonl.py", line 92
File "C:\development\projects\my-test-stuff\.meltano\loaders\target-jsonl\venv\lib\site-packages\target_jsonl.py", line 54
    validators[o['stream']].validate((o['record']))
File "C:\development\projects\my-test-stuff\.meltano\loaders\target-jsonl\venv\lib\site-packages\jsonschema\validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: False is not of type 'string'
 
Failed validating 'type' in schema['properties']['TestColumn1']: 
    {'type': ['string']} 
On instance['TestColumn1']:
    False
Loader failed 
```

**Comment by BuzzCutNorman** [comment]
Testing of the command `meltano run tap-mssql target-mssql` with the PR in place was successful.  The file `dbo-TestTable-jsonl` was generated and had the following content.

```
{"Id": 1, "TestColumn1": false, "TestColumn2": true}
``` 

I am going to merge the PR which will close this issue.
